name: pcorr
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - rdkit
  - networkx
  - pip
  - pip:
      - streamlit
      - st-aggrid
      - plotly
      - seaborn
      - scikit-learn